//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSuite {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestSuite.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://abantecart.codifyme.co.nz/.
        /// </summary>
        internal static string baseUrl {
            get {
                return ResourceManager.GetString("baseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string browserType {
            get {
                return ResourceManager.GetString("browserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestData\Excel\Data.xlsx.
        /// </summary>
        internal static string excelTestData {
            get {
                return ResourceManager.GetString("excelTestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dummy Client.
        /// </summary>
        internal static string metaData_Client {
            get {
                return ResourceManager.GetString("metaData_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dummy Project.
        /// </summary>
        internal static string metaData_Project {
            get {
                return ResourceManager.GetString("metaData_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anthony Regis.
        /// </summary>
        internal static string metaData_TestAnalyst {
            get {
                return ResourceManager.GetString("metaData_TestAnalyst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Regression.
        /// </summary>
        internal static string metaData_TestingType {
            get {
                return ResourceManager.GetString("metaData_TestingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dummy UAT.
        /// </summary>
        internal static string metData_TestEnvironment {
            get {
                return ResourceManager.GetString("metData_TestEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestReport.
        /// </summary>
        internal static string reportPath {
            get {
                return ResourceManager.GetString("reportPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestReport\Screenshots.
        /// </summary>
        internal static string screenshotPath {
            get {
                return ResourceManager.GetString("screenshotPath", resourceCulture);
            }
        }
    }
}
