//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSuite {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestSuite.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://abantecart.codifyme.co.nz/.
        /// </summary>
        internal static string BaseUrl {
            get {
                return ResourceManager.GetString("BaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string BrowserType {
            get {
                return ResourceManager.GetString("BrowserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestData\Excel\Data.xlsx.
        /// </summary>
        internal static string ExcelDataPath {
            get {
                return ResourceManager.GetString("ExcelDataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passw0rd.
        /// </summary>
        internal static string MemberPassword {
            get {
                return ResourceManager.GetString("MemberPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to testaccount.
        /// </summary>
        internal static string MemberUsername {
            get {
                return ResourceManager.GetString("MemberUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dummy Client.
        /// </summary>
        internal static string MetaData_Client {
            get {
                return ResourceManager.GetString("MetaData_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dummy Project.
        /// </summary>
        internal static string MetaData_Project {
            get {
                return ResourceManager.GetString("MetaData_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anthony Regis.
        /// </summary>
        internal static string MetaData_TestAnalyst {
            get {
                return ResourceManager.GetString("MetaData_TestAnalyst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Regression.
        /// </summary>
        internal static string MetaData_TestingType {
            get {
                return ResourceManager.GetString("MetaData_TestingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dummy UAT.
        /// </summary>
        internal static string MetData_TestEnvironment {
            get {
                return ResourceManager.GetString("MetData_TestEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestReport.
        /// </summary>
        internal static string ReportPath {
            get {
                return ResourceManager.GetString("ReportPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestReport\Screenshots.
        /// </summary>
        internal static string ScreenshotPath {
            get {
                return ResourceManager.GetString("ScreenshotPath", resourceCulture);
            }
        }
    }
}
